# Generated by Django 5.2.4 on 2025-08-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_faceembedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faceembedding',
            options={'verbose_name': 'Face Embedding', 'verbose_name_plural': 'Face Embeddings'},
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='embedding_data',
            field=models.TextField(help_text='JSON serialized face embedding data'),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='image_filename',
            field=models.CharField(help_text='Original filename of the uploaded image', max_length=255),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='name',
            field=models.CharField(help_text='Name of the person', max_length=100, unique=True),
        ),
    ]
