# Generated by Django 5.2.4 on 2025-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
