# Generated by Django 5.2.5 on 2025-08-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='is_admin_approved',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='active', max_length=10),
        ),
    ]
