# Generated by Django 5.2.5 on 2025-08-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_remove_roommember_is_admin_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
