# Generated by Django 5.2.5 on 2025-08-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_roommember_is_admin_approved_alter_roommember_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_name',
        ),
    ]
