# Generated by Django 5.2.4 on 2025-08-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_ai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssistantInteraction',
        ),
    ]
